language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:
  - go get -u github.com/mattn/goveralls

install:
  - go get github.com/yanzay/log
  - go get github.com/go-telegram-bot-api/telegram-bot-api

script:
  - go test -v -race -cover ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
